import { Product } from './types';

export const CATEGORIES = [
  {
    id: 'c1',
    name: 'Premium Abayas',
    description: 'Elegant drapes for every occasion with luxury finishes and detailing.',
    image: '/images/abaya-black.jpg',
    itemCount: 124,
  },
  {
    id: 'c2',
    name: 'Luxury Hijabs',
    description: 'Silk, Chiffon, and Cotton blends in a curated spectrum of colors.',
    image: '/images/hijab-collection.jpg',
    itemCount: 89,
  },
  {
    id: 'c3',
    name: 'Niqabs & Veils',
    description: 'Breathable layered coverage featuring delicate lace and premium chiffon.',
    image: '/images/niqab-lace.jpg',
    itemCount: 56,
  },
  {
    id: 'c4',
    name: 'Modest Dresses',
    description: 'Contemporary structured silhouettes for the modern modest woman.',
    image: '/images/dress-blush.jpg',
    itemCount: 42,
  },
  {
    id: 'c5',
    name: 'Khimars',
    description: 'Flowing overhead coverings in premium breathable fabrics.',
    image: '/images/khimar-black.jpg',
    itemCount: 35,
  },
  {
    id: 'c6',
    name: 'Accessories',
    description: 'Underscarves, pins, brooches and prayer sets to complete your look.',
    image: '/images/hijab-collection.jpg',
    itemCount: 67,
  },
  {
    id: 'c7',
    name: 'Socks & Hosiery',
    description: 'Premium knee-highs, ankle socks and hosiery from trusted brands like Silvy & Sandy.',
    image: '/images/sandy-socks.webp',
    itemCount: 28,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Royal Silk Wrap Abaya',
    category: 'Premium Abayas',
    price: 85000,
    dozenPrice: 72000,
    description: 'Luxurious silk wrap abaya with hand-finished seams and gold-tipped belt closure. Breathable lining for all-day comfort.',
    isNew: true,
    image: '/images/abaya-black.jpg',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p2',
    name: 'Medina Georgette Hijab',
    category: 'Luxury Hijabs',
    price: 12500,
    dozenPrice: 10000,
    description: 'Premium georgette hijab with delicate rolled edges. Lightweight, non-slip, and perfect for everyday wear.',
    isNew: false,
    image: '/images/hijab-collection.jpg',
  },
  {
    id: 'p3',
    name: '3-Layer Breathable Niqab',
    category: 'Niqabs & Veils',
    price: 18000,
    dozenPrice: 15000,
    description: 'Three-layer chiffon niqab with adjustable tie-back. Breathable design for tropical climates.',
    isNew: false,
    image: '/images/niqab-lace.jpg',
  },
  {
    id: 'p4',
    name: 'Dubai Crepe Maxi Dress',
    category: 'Modest Dresses',
    price: 65000,
    dozenPrice: 55000,
    description: 'Flowing crepe maxi dress with structured shoulders and hidden pockets. Perfect for formal occasions.',
    isNew: true,
    image: '/images/dress-blush.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p5',
    name: 'Embroidered Bisht Abaya',
    category: 'Premium Abayas',
    price: 110000,
    dozenPrice: 95000,
    description: 'Statement bisht-style abaya with intricate gold thread embroidery along the front panels and cuffs.',
    isNew: false,
    image: '/images/abaya-navy.jpg',
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p6',
    name: 'Premium Jersey Hijab Set',
    category: 'Luxury Hijabs',
    price: 25000,
    dozenPrice: 20000,
    description: 'Set of 3 premium jersey hijabs in complementary tones. Stretchy, opaque, and wrinkle-resistant.',
    isNew: true,
    image: '/images/hijab-collection.jpg',
  },
  {
    id: 'p7',
    name: 'Structured Khimar',
    category: 'Khimars',
    price: 32000,
    dozenPrice: 27000,
    description: 'Structured overhead khimar with face-framing design. Made from premium nida fabric for a clean drape.',
    isNew: true,
    image: '/images/khimar-black.jpg',
  },
  {
    id: 'p8',
    name: 'Pleated Chiffon Dress',
    category: 'Modest Dresses',
    price: 58000,
    dozenPrice: 49000,
    description: 'Elegant pleated chiffon dress with inner lining. Features gathered waist and flowy skirt.',
    isNew: false,
    image: '/images/dress-blush.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p9',
    name: 'Butterfly Abaya - Noir',
    category: 'Premium Abayas',
    price: 95000,
    dozenPrice: 80000,
    description: 'Classic butterfly-cut abaya in jet black premium nida fabric. Wide sleeves with subtle lace trim.',
    isNew: false,
    image: '/images/abaya-black.jpg',
    sizes: ['Free Size'],
  },
  {
    id: 'p10',
    name: 'Lace-Trimmed Niqab',
    category: 'Niqabs & Veils',
    price: 22000,
    dozenPrice: 18500,
    description: 'Elegant single-layer niqab with delicate floral lace border. Adjustable nose wire for secure fit.',
    isNew: true,
    image: '/images/niqab-lace.jpg',
  },
  {
    id: 'p11',
    name: 'Instant Jersey Hijab',
    category: 'Luxury Hijabs',
    price: 8500,
    dozenPrice: 7000,
    description: 'Pull-on instant hijab in stretchy jersey. No pins needed — perfect for busy mornings.',
    isNew: false,
    image: '/images/hijab-collection.jpg',
  },
  {
    id: 'p12',
    name: 'Two-Piece Jilbab Set',
    category: 'Khimars',
    price: 45000,
    dozenPrice: 38000,
    description: 'Complete two-piece jilbab set with overhead khimar and matching skirt. Wrinkle-free travel fabric.',
    isNew: true,
    image: '/images/khimar-black.jpg',
    sizes: ['S/M', 'L/XL'],
  },
  {
    id: 'p13',
    name: "A'abidah Premium Niqob",
    category: 'Niqabs & Veils',
    price: 15000,
    dozenPrice: 12500,
    description: "Premium boxed A'abidah niqob with elegant gold packaging. High-quality breathable fabric with a refined finish — perfect for daily wear and gifting.",
    isNew: true,
    image: '/images/aabidah-niqob.jfif',
  },
  {
    id: 'p14',
    name: 'Sandy Knee-High Socks',
    category: 'Socks & Hosiery',
    price: 5500,
    dozenPrice: 4500,
    description: 'Sandy by Silvy — premium knee-high socks with a finger toe design. Lightweight, durable, and made in Egypt. Available in multiple shades.',
    isNew: true,
    image: '/images/sandy-socks.webp',
  },
  {
    id: 'p15',
    name: 'Silvy Socks Pack',
    category: 'Socks & Hosiery',
    price: 4500,
    dozenPrice: 3800,
    description: 'Original Silvy brand socks in skin-tone shades. Soft, breathable, and long-lasting — ideal for everyday modest wear under abayas and dresses.',
    isNew: true,
    image: '/images/silvy-socks.webp',
  },
];
